### ISSUE TITLE
V4.0.0

### ISSUE THREAD

**Issue by aichbauer** [aichbauer/styled-bootstrap-components#51]
Thanks to the active contributions of @michaelkrukov we will soon be releasing a new version 4.0.0

I would like to see this issue as a discussion board for the next version v4.0.0

As the next version has some breaking changes in it I would like to make a list of what is missing that we can implement before v4.0.0.

So I look forward for you ideas...

**Comment by aakhan89** [comment]
Documentation
Examples with each props/component etc..

**Comment by michaelkrukov** [comment]
I think it would be good to make colors in default theme use newly introduced `colorScheme`. Maybe we should organize transition animations as a part of `styled-base-components` package. Like modal's Fade probably can be used in other parts of projects and components like popovers and tooltips. There are packages for creating transitions, but I guess we can just use some plain CSS transitions for the sake of simplicity and improve it later if needed. Some inspirations can be drawn from `react-transition-group`. 

It seems that documentation (storybook) needs some polishing. I think there is something wrong with how it looks and works (at least with readme button). Examples from readme and stories should be more concise to avoid creating `.md` and `.jsx` files for embedding them into stories. Also, I think creating `propTypes` for components is important. 

So I think it would be nice to create and close following issues before the next release: `Feat: Use colorScheme in default theme`, `Feat: Add organized transitions`, `Feat: Update storybook and readme files` and `Feat: Add propTypes to components`.

Updating and organizing documentation will lead to a better understanding of the use cases and will allow us to better understand what and how should be changed before the release of v4. I don't think we are bound by some deadlines, so we can take time to do research and develop quality release until it will be ready.

**Comment by JohnTheo13** [comment]
With regards to the Documentation a fast and nice implementation would be to use storybook's [withInfo](https://github.com/storybookjs/storybook/tree/master/addons/info)  with a custom table component (reusable across stories)

**Comment by aichbauer** [comment]
@aakhan89 Yes, we definitely should improve the documentation. Could you give us more details on how you want to improve the dropdown component?

@michaelkrukov indeed, the readme files are not working anymore, and should be fixed. 
Can you explain a bit more in details about the `colorScheme`? 
I like the idea of having some reusable transitions, which we can use for the tooltips and popovers. 

@JohnTheo13 thanks for the tip.

1.) Documentation is something we are lacking the most currently... So to improve that, we should have a good and working example for all components. We should also fix, the readme button, or find some other way to include the readme again, so that the user has the most important information. 

2.) Reusable transition, that are reusable for other components.
2.1) update tooltip, and popover?

3.) Improve the theme and colorScheme?

4.) improve dropdown component.

5.) We need documentation for the theme.

**Comment by michaelkrukov** [comment]
@aichbauer For example, `buttonPrimaryBackgroundColor` in `color` object only used in button's `backgroundColor` and has same values as `blue`. If I want to change all primary component's blue to some other color (or a different shade of blue), I will have to change its color in every component's theme configurations instead of just specifying different `primary` color in `colorScheme`. Also "proxy" fields like `buttonPrimaryBackgroundColor` not really helpful as its change will often lead to a need for changes in other fields like `colorOutline`, e.t.c.  

I think custom styling with themes can be improved by implementing some inheritance. 
This will require a change in util's methods like `padding` and `color`. They should accept props, component name, and the desired value's name and return found value. So for props with primary `color(props, "button", "backgroundColor")` should look for `backgroundColor` in `theme.button.primary.backgroundColor`, then in `defaultTheme.button.primary.backgroundColor`, in `theme.colorScheme.primary` and if nothing is found, `defaultTheme.colorScheme.primary` will be used.
Usage of `defaultTheme` can solve difficulties with the deep merging of objects. Helper function `color` also should accept forth argument for specifying the key in `colorScheme` (`color(props, "button", "colorHoverActive", "dark")` -> `theme.colorScheme.primaryDark`). Otherwise, it would be difficult to get color value for shadows. And yes, it will require additional fields in `colorScheme` like `primaryDark`, `primaryLight`, e.t.c.

Also, in my opinion, `default` in component's themes (like `theme.button.default`) should be replaced with plain redirection to `theme.*.secondary`.

**Comment by michaelkrukov** [comment]
While looking at styles, I also found that `ButtonGroup` actually has styles that change buttons' style.

```scss
& > button {
    line-height: 1.5;
    position: relative;
    flex: 0 1 auto;
    &:hover {
        z-index: 1;
    };
    ${(props) => size(props)};
};
```

I don't think that the library should operate on plain elements. If I recall correctly, this can be replaced with `& > ${Button} { ... }`. That way it will work with the button's class and any element.

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 Yes, we definitely should improve the documentation. Could you give us more details on how you want to improve the dropdown component?
> 
@aichbauer Sure, I will show you with example

**Comment by aichbauer** [comment]
@michaelkrukov you are right about the `<ButtonGroup />`, I think this is exactly how it should work...

I think the idea with the colorscheme is good... and would improve the usability of styling your own components...

Do we have a idea of how to improve the docs with the readme? I used [docz](https://www.docz.site/) for all of my latest projects... Maybe we switch or do you think we should stay with storybook?

**Comment by michaelkrukov** [comment]
@aichbauer wow, it's been a while since I wrote here. So, I'll look into the ideas I mentioned when I'll have time. 

Basically, stories' improvement is simplification (usage of hooks, removing unnecessary plugins, props, e.t.c.). And for readme files, I think they may be more concise: TOC (files are not that big for that), "Why?", "Related" (I don't think that's very relevant information) and "License" (there is a file LICENCE for that and files in `package.json`) sections can be removed. "Installation" and "Usage" can be reduced a bit (it's better to refer users to stories or documentation, and installation can be written as just two lines with comments).

I started working on improving storybook, but it doesn't have too much work done, so it's ok to switch. Personally, I don't have problems with storybook.

**Comment by michaelkrukov** [comment]
@aichbauer to allow users to reference `colorScheme` values in configuration, as well as use just colors, we'll have to allow some kind of reference in the config. Functions, for example, that will pull the required color from the current theme. That means these functions should have access to it. This will make config more complex, but, I guess, it's worth it. I will create a new issue for discussion of possible architectures and APIs later.

**Comment by aichbauer** [comment]
@michaelkrukov then I think we improve our stories so that we do not have to link the readme file... that would be a much simpler approach...  

I personally think that "Why" is an important part (but could have an improvement [rm point 2 and 3, and tell why use this library and whats the difference to other solutions]) of an readme... so everyone who is coming from `bootstrap` or `reactstrap` sees why we use `styled-bootstrap-components` and whats the differnce to other solutions... point 2 and 3 of why is not very relevant I guess... 

The related section is really not very relevant, could be removed. I'm with you on this topic...

The License section is just a common way of how a readme is structured... Its true that we have a LICENSE file... But in my opinion a readme file is also a good way to show who has build something... so maybe we do not need the license section, but I would like it if we can show who worked on this library... maybe we use something like [all-contributors](https://github.com/all-contributors/all-contributors#emoji-key) to give credits to everyone who worked on this project... what do you think?

The installation section can be reduced to one line... thats true...

I think the usage section should be pretty detailed, because not everyone is switching from github to the documention... I always like it if there are detailed instructions in the readme... but maybe I am alone on  this topic...

About the `colorScheme`: I am 100% into that. I think that this improvement for customization is worth the more complex config... I personally think that everyone who uses this library can definitively profit from your idea...

**Comment by michaelkrukov** [comment]
@aichbauer "Usage" can be simplified by, for example, using React's hooks, e.t.c. I agree that readme should have enough information to use component.  

We can add contributors to readme files, but I think something like a list with names, links and [emojies](https://allcontributors.org/docs/en/emoji-key) describing contribution categories will suffice. And keeping the license section is good.

**Comment by aichbauer** [comment]
@michaelkrukov first off, thanks a lot for doing so much work on v4.0.0 👍 

Do you think that we need any improvement before we release v4.0.0? Right now, I think you have implemented everything that we have discussed for version v4.0.0.

**Comment by michaelkrukov** [comment]
@aichbauer, I think I implemented enough features to release a new version. I already want to use utilities and transitions in projects :D
