### ISSUE TITLE
Table - valign td

### ISSUE THREAD

**Issue by joetidee** [aichbauer/styled-bootstrap-components#9]
What is the best way to vertical align content within `<td>` elements?

**Comment by aichbauer** [comment]
This is more a generell question about css and it is probably better to ask this kind of questions that are not directly related to this library on [stackoverflow](https://stackoverflow.com/search?q=vertical+align+in+td).

But to answer your question: the easiest way to vertical align the content within `<td>` elements is to:

you can use the following args: `baseline | sub  | super | text-top | text-bottom | middle | top | bottom | <%> | <length> | inherit`

```css
td {
  vertical-align: middle; /* to center it vertical */
}
```

to to this with styled components you have to:

```jsx
import styled from 'styled-components';

const Td = styled.td`
  vertical-align: middle; // to center it vertical
`;
```

now you can use this within your component as `<Td>I am vertical centered</Td>`

**Comment by joetidee** [comment]
This question was directed at the library, i.e. there are no props to allow vertical alignment within the <td> elements and I thought that there should be.

**Comment by aichbauer** [comment]
Okay, I am open for ideas.

The current implementation does not even have a own `<Td>` component. That is why there are no props for this.

The question is if it would make sense to create a own `<Td>` component. Currently all Components are based on the class names that were used in bootstrap 4. Thats why there is no implementation for `<Td>` because there is no class explicitly for `<Td>`.

But what I think would be a good idea is, that we should implement the [utility components](https://getbootstrap.com/docs/4.1/utilities/vertical-align/) from bootstrap... There is also a utility for vertical align. What do you think?

**Comment by joetidee** [comment]
I can't see how these utility components can benefit a Td styled component, for example (?)

**Comment by aichbauer** [comment]
We could use the utility components like:

```jsx
<td>
  <VerticalAlign center>
    Centered text
  </VerticalAlign>
</td>
```

But I don't think that we need a particular new component for a `<Td>`. 

If you would like to have all `<td>` in you table to be vertical aligned you could just use:

```jsx
const Tr = styled.tr`
  & > td {
    vertical-align: center;
  }
`;
```

and then just use this component.

Do you have any ideas? Because without you giving me examples I can not decide wether we can implement that or not.

**Comment by aichbauer** [comment]
close due to no response.
